spring:
  datasource:
    ds-0:
      hikari:
        jdbc-url: jdbc:mysql://172.16.2.100:3306/ds1
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: Mysql@2017
        minimum-idle: 10
        maximum-pool-size: 200
        pool-name: DS0HikariCP
        connection-timeout: 30000
        connection-test-query: select 1
        max-lifetime: 600000
        idle-timeout: 120000
        data-source-properties: {cachePrepStmts: true, prepStmtCacheSize: 250, prepStmtCacheSqlLimit: 2048, useServerPrepStmts: true}
    ds-1:
      hikari:
        jdbc-url: jdbc:mysql://172.16.2.100:3306/ds2
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: Mysql@2017
        minimum-idle: 10
        maximum-pool-size: 200
        pool-name: DS1HikariCP
        connection-timeout: 30000
        connection-test-query: select 1
        max-lifetime: 600000
        idle-timeout: 120000
        data-source-properties: {cachePrepStmts: true, prepStmtCacheSize: 250, prepStmtCacheSqlLimit: 2048, useServerPrepStmts: true}